"""LogSeeker標準タクソノミー（docs/taxonomy.md から自動生成。手で編集しない）。

生成: python3 backend/tools/gen_taxonomy.py docs/taxonomy.md backend/app/taxonomy_master.py

v12 §4.1.1 の「受信フィールド」= payload内のKEYのうち ALL_KEYS と完全一致するものだけ。
ALL_KEYS はClassに依存しない全体集合であり、Class VALUEはこの一覧を制限しない
（taxonomy.md §3）。CLASS_HINTS は日本語表示名・初期表示の手がかりに過ぎず、
ここに無いKEYを選べなくする用途には使わない。
"""

# 全Taxonomy KEY（770件）: KEY -> 型
ALL_KEYS: dict[str, str] = {
    'accesses': 'string',
    'accessgroup': 'string',
    'accessmask': 'string',
    'accountdomain': 'string',
    'accountid': 'string',
    'accountname': 'string',
    'ackduration': 'integer',
    'acktime': 'string',
    'acktimeutc': 'string',
    'aclname': 'string',
    'aclnumber': 'integer',
    'acquire_attempt_count': 'number',
    'acquired_at_time': 'string',
    'acquired_by': 'string',
    'action': 'string',
    'actioncode': 'integer',
    'activity': 'string',
    'activityid': 'string',
    'actor': 'string',
    'addl': 'string',
    'ag_count': 'number',
    'agent': 'string',
    'agentdomain': 'string',
    'agenthostname': 'string',
    'agentid': 'string',
    'agentip': 'string',
    'agentloggedonusers': 'string',
    'agentmac': 'string',
    'agentos': 'string',
    'agentstatus': 'string',
    'agentversion': 'string',
    'alert_product': 'string',
    'alert_time': 'string',
    'alertdomain': 'string',
    'alerted': 'boolean',
    'alerturi': 'string',
    'alerturl': 'string',
    'alexa_rank': 'number',
    'ami': 'string',
    'ami_description': 'string',
    'ami_name': 'string',
    'ami_owner': 'string',
    'ami_platform': 'string',
    'analyzer': 'string',
    'answer': 'string',
    'apipv4': 'ipv4',
    'apipv6': 'ipv6',
    'apmac': 'mac',
    'apname': 'string',
    'appcategory': 'string',
    'appdesc': 'string',
    'appid': 'string',
    'application': 'string',
    'apppath': 'string',
    'appproperties': 'string',
    'archive_id': 'string',
    'args': 'string',
    'asn': 'string',
    'asset': 'object',
    'assets': 'array',
    'attachment': 'string',
    'attack': 'string',
    'attackinfo': 'string',
    'attemptingAcquire': 'boolean',
    'audit_acct': 'string',
    'audit_res': 'string',
    'audit_type': 'string',
    'audititemid': 'string',
    'auth': 'string',
    'auth_success': 'boolean',
    'authmethod': 'string',
    'authoritativeanswer': 'boolean',
    'av_hits': 'string',
    'ax_malicious_alerts': 'string',
    'ax_score': 'boolean',
    'bay': 'string',
    'behavior': 'string',
    'binary_can_sleep': 'string',
    'binary_languages': 'string',
    'binarystate': 'boolean',
    'bytes': 'integer',
    'bytespersec': 'number',
    'cachetype': 'string',
    'cacheval': 'string',
    'callid': 'string',
    'callingdomain': 'string',
    'callinglogonid': 'string',
    'callingsrcip': 'string',
    'callingsrcipv6': 'ipv6',
    'callinguid': 'string',
    'callingusername': 'string',
    'callingusersecurityid': 'string',
    'capture_password': 'boolean',
    'category': 'string',
    'cc': 'string',
    'cert_chain': 'string',
    'cert_chain_fuids': 'string',
    'cert_count': 'number',
    'cert_errors': 'string',
    'cert_permanent': 'boolean',
    'cert_type': 'string',
    'certname': 'string',
    'certsubject': 'string',
    'charencoding': 'string',
    'cidr': 'string',
    'cipher': 'string',
    'city': 'string',
    'class': 'string',
    'classid': 'string',
    'client': 'string',
    'client_cert_chain': 'string',
    'client_cert_chain_fuids': 'string',
    'client_depth': 'number',
    'client_key_exchange_seen': 'boolean',
    'client_ticket_empty_session_seen': 'boolean',
    'client_uuid': 'string',
    'clientissuersubject': 'string',
    'clientsubject': 'string',
    'clientvars': 'string',
    'closeduration': 'integer',
    'closetime': 'string',
    'closetimeutc': 'string',
    'cmdarg': 'string',
    'cnchost': 'string',
    'cncipv4': 'string',
    'cncport': 'number',
    'compile_time': 'string',
    'compression_alg': 'string',
    'confidence': 'string',
    'connectionid': 'string',
    'connections': 'integer',
    'connstate': 'string',
    'containduration': 'integer',
    'containtime': 'string',
    'containtimeutc': 'string',
    'content': 'string',
    'context_tags': 'string',
    'continent': 'string',
    'cookievars': 'string',
    'count': 'number',
    'count_updated_at_time': 'string',
    'country': 'string',
    'countrycode': 'string',
    'createdtime': 'string',
    'createdtimeutc': 'string',
    'creatorprocessid': 'string',
    'current_status': 'string',
    'current_status_txt': 'string',
    'curve': 'string',
    'customer': 'string',
    'customercode': 'string',
    'cveid': 'string',
    'cwd': 'string',
    'data_channel': 'string',
    'day': 'string',
    'dbinstance': 'string',
    'dbname': 'string',
    'dbtable': 'string',
    'dcid': 'integer',
    'defgw': 'string',
    'depth': 'string',
    'description': 'string',
    'desktop_height': 'number',
    'desktop_width': 'number',
    'detect_ruleids': 'array',
    'detect_rulematch': 'object',
    'detect_rulematches': 'array',
    'detect_rulenames': 'array',
    'detectedtime': 'string',
    'detectedtimeutc': 'string',
    'deviceid': 'string',
    'devicename': 'string',
    'devicetype': 'string',
    'dhcpscope': 'string',
    'direction': 'string',
    'disabled_aids': 'number',
    'disk': 'string',
    'disposition': 'string',
    'distance': 'number',
    'dns_lookups': 'string',
    'domain': 'string',
    'domain_category': 'string',
    'done': 'boolean',
    'driver': 'string',
    'dropped': 'boolean',
    'dstareacode': 'string',
    'dstasn': 'string',
    'dstasorg': 'string',
    'dstcity': 'string',
    'dstcountry': 'string',
    'dstcountrycode': 'string',
    'dstdomain': 'string',
    'dstelevation': 'number',
    'dsthost': 'string',
    'dstiddcode': 'string',
    'dstipv4': 'string',
    'dstipv6': 'string',
    'dstisp': 'string',
    'dstlatitude': 'number',
    'dstlocation': 'string',
    'dstlongitude': 'number',
    'dstmac': 'string',
    'dstmcc': 'string',
    'dstmnc': 'string',
    'dstmobilebrand': 'string',
    'dstnatrule': 'string',
    'dstnetspeed': 'string',
    'dstport': 'integer',
    'dstregion': 'string',
    'dstserver': 'ipv4',
    'dsttimezone': 'string',
    'dstusagetype': 'string',
    'dstweatherstationcode': 'string',
    'dstweatherstationname': 'string',
    'dstzipcode': 'string',
    'dstzone': 'string',
    'duration': 'number',
    'dynamic_indicators': 'string',
    'enc_appdata_bytes': 'number',
    'enc_appdata_packages': 'number',
    'encodedmsg': 'string',
    'encryption': 'string',
    'encryption_level': 'string',
    'endtime': 'string',
    'endtimeutc': 'string',
    'enriched': 'boolean',
    'enrichment_error': 'string',
    'enrichment_start': 'string',
    'enrichment_status_txt': 'string',
    'errorcode': 'integer',
    'errormessage': 'string',
    'escalateduration': 'integer',
    'escalatetime': 'string',
    'escalatetimeutc': 'string',
    'established': 'boolean',
    'eventid': 'string',
    'eventlog': 'string',
    'eventname': 'string',
    'eventreceivedtime': 'date-time',
    'eventtime': 'string',
    'eventtimeutc': 'string',
    'eventtype': 'string',
    'evil_flag': 'boolean',
    'evil_indicators': 'string',
    'exceptionlvl': 'integer',
    'exceptionmsg': 'string',
    'exceptiontype': 'string',
    'expirationtime': 'string',
    'expirationtimeutc': 'string',
    'extendedproperties': 'object',
    'extension': 'string',
    'extnatip': 'string',
    'extnatipv6': 'ipv6',
    'extracted': 'boolean',
    'facility': 'string',
    'family': 'string',
    'file_accessed_time': 'string',
    'file_created_time': 'string',
    'file_enrichment_status': 'string',
    'file_mime_type': 'string',
    'file_modified_time': 'string',
    'file_owner': 'string',
    'file_signed': 'boolean',
    'filedesc': 'string',
    'fileid': 'string',
    'filename': 'string',
    'filepath': 'string',
    'filepermission': 'string',
    'filetype': 'string',
    'filter': 'string',
    'fingerprint': 'string',
    'firstseen': 'string',
    'firstseenutc': 'string',
    'flagtype': 'string',
    'flagval': 'string',
    'force_log': 'boolean',
    'foreigninterface': 'string',
    'fqdn_nucleus_summary': 'string',
    'from': 'string',
    'function': 'string',
    'fwdipv4': 'ipv4',
    'fwdipv6': 'ipv6',
    'gid': 'integer',
    'group': 'string',
    'groupdomain': 'string',
    'groupsecurityid': 'string',
    'gwipv4': 'ipv4',
    'gwipv6': 'ipv6',
    'handleid': 'integer',
    'hasMTAReport': 'boolean',
    'has_cert_table': 'boolean',
    'has_debug_data': 'boolean',
    'has_export_table': 'boolean',
    'has_import_table': 'boolean',
    'hash': 'string',
    'heartbleed_detected': 'boolean',
    'hierarchy': 'string',
    'history': 'string',
    'host': 'string',
    'host_count': 'number',
    'host_key': 'string',
    'host_key_alg': 'string',
    'hostname': 'string',
    'hour': 'string',
    'httpbody': 'string',
    'httpmethod': 'string',
    'hx_alert_id': 'number',
    'icid': 'integer',
    'impact': 'string',
    'imphash': 'string',
    'import_hash_count': 'number',
    'info': 'string',
    'infocode': 'string',
    'infomsg': 'string',
    'inreplyto': 'string',
    'instance_id': 'string',
    'instance_profile': 'string',
    'instance_tags': 'object',
    'instance_type': 'string',
    'instanceid': 'string',
    'integritylevel': 'string',
    'intel_context': 'object',
    'intel_context_unavailable': 'boolean',
    'intel_match_observable': 'object',
    'intel_matches': 'array',
    'intelalertmessage': 'string',
    'intelalertnotes': 'string',
    'inteleventid': 'string',
    'intelmalwarefamily': 'string',
    'intelmatchclass': 'string',
    'intelmatchfield': 'string',
    'intelmatchtime': 'string',
    'intelmatchvalue': 'string',
    'intelmeta_cbid': 'integer',
    'intelmeta_mid': 'integer',
    'intelscore': 'string',
    'inteltags': 'array',
    'inteltype': 'integer',
    'inteluuid': 'string',
    'intelwhitelisted': 'object',
    'interface': 'string',
    'interfaceid': 'string',
    'intnatip': 'string',
    'iocname': 'string',
    'iocnames': 'string',
    'ip': 'string',
    'ip_nucleus_summary': 'string',
    'ipmask': 'string',
    'ipv4': 'string',
    'ipv6': 'string',
    'is_64bit': 'boolean',
    'is_exe': 'boolean',
    'is_malware': 'boolean',
    'isacquired': 'boolean',
    'isorig': 'boolean',
    'issuer': 'string',
    'issuersubject': 'string',
    'issuetime': 'string',
    'issuetimeutc': 'string',
    'job': 'string',
    'jobid': 'string',
    'kex_alg': 'string',
    'keypair': 'string',
    'keywords': 'string',
    'language': 'string',
    'last_auth_requested': 'string',
    'last_originator_heartbeat_request_size': 'number',
    'lastaccessedtime': 'string',
    'lastaccessedtimeutc': 'string',
    'lastalertid': 'string',
    'lastmodifiedtime': 'string',
    'lastmodifiedtimeutc': 'string',
    'lastscannedtime': 'string',
    'lastscannedtimeutc': 'string',
    'lastseen': 'string',
    'lastseenutc': 'string',
    'lat': 'string',
    'length': 'string',
    'level': 'integer',
    'linenumber': 'integer',
    'local_resp': 'boolean',
    'localinterface': 'string',
    'localorig': 'boolean',
    'logged': 'boolean',
    'logonguid': 'string',
    'logonid': 'string',
    'logontype': 'string',
    'logontypeid': 'integer',
    'long': 'string',
    'mac': 'string',
    'mac_alg': 'string',
    'macoui': 'string',
    'mailbox': 'string',
    'mailfrom': 'string',
    'malwarefamily': 'string',
    'malwarename': 'string',
    'malwaretype': 'string',
    'malwarevariant': 'string',
    'manufacturer': 'string',
    'mcube_list': 'string',
    'md5': 'string',
    'member': 'string',
    'memberdomain': 'string',
    'membersecurityid': 'string',
    'message': 'string',
    'message_id': 'string',
    'meta_cb_c': 'string',
    'meta_cb_cn': 'string',
    'meta_cb_l': 'string',
    'meta_cb_on': 'string',
    'meta_cb_oun': 'string',
    'meta_cb_st': 'string',
    'meta_cbid': 'integer',
    'meta_cbname': 'string',
    'meta_cid': 'string',
    'meta_cust_name': 'string',
    'meta_i': 'string',
    'meta_iid': 'integer',
    'meta_mid': 'integer',
    'meta_odt': 'string',
    'meta_ohn': 'string',
    'meta_omh': 'string',
    'meta_oml': 'integer',
    'meta_opri': 'string',
    'meta_rrm': 'string',
    'meta_rts': 'integer',
    'meta_rule': 'string',
    'meta_sip4': 'integer',
    'meta_sip6': 'string',
    'meta_sp': 'integer',
    'meta_sts': 'integer',
    'meta_ts': 'integer',
    'metaclass': 'string',
    'method': 'string',
    'mid': 'integer',
    'mimetype': 'string',
    'minute': 'string',
    'missingbytes': 'integer',
    'mode': 'string',
    'modifiedproperties': 'object',
    'month': 'string',
    'msg': 'string',
    'msr_ruleids': 'array',
    'network': 'string',
    'network_connections': 'string',
    'next_protocol': 'string',
    'nick': 'string',
    'node': 'string',
    'notice': 'boolean',
    'nuc_attribution_date': 'string',
    'nuc_md5_attribution': 'string',
    'number': 'integer',
    'object': 'string',
    'objectserver': 'string',
    'objecttype': 'string',
    'ocsp_response': 'string',
    'ocsp_status': 'string',
    'offset': 'string',
    'old_period': 'integer',
    'operationid': 'string',
    'origin': 'string',
    'original_company_name': 'string',
    'original_description': 'string',
    'original_file_name': 'string',
    'originationtime': 'string',
    'originationtimeutc': 'string',
    'originator_heartbeats': 'number',
    'os': 'string',
    'overflowbytes': 'integer',
    'packet_segment': 'string',
    'packets': 'integer',
    'packettype': 'string',
    'page': 'integer',
    'parameters': 'object',
    'parentfileid': 'string',
    'pargs': 'string',
    'partition': 'string',
    'passive': 'boolean',
    'password': 'string',
    'peak': 'number',
    'pecreatedtime': 'string',
    'pecreatedtimeutc': 'string',
    'peer': 'string',
    'pending_commands': 'string',
    'perchg': 'number',
    'period': 'integer',
    'pid': 'integer',
    'policy': 'string',
    'policyid': 'string',
    'portid': 'string',
    'ppid': 'integer',
    'pprocess': 'string',
    'pprocessguid': 'string',
    'pprocesspath': 'string',
    'prevscore': 'number',
    'printer': 'string',
    'priority': 'string',
    'privileges': 'string',
    'privlevel': 'string',
    'process': 'string',
    'processguid': 'string',
    'processid': 'string',
    'processpath': 'string',
    'product': 'string',
    'profile': 'string',
    'program': 'string',
    'protocol': 'string',
    'protocolver': 'string',
    'protoid': 'integer',
    'providerguid': 'string',
    'proxied': 'string',
    'proxydstipv4': 'ipv4',
    'proxysrcipv4': 'string',
    'proxystatuscode': 'integer',
    'query': 'string',
    'queryclass': 'integer',
    'queryclassname': 'string',
    'querytype': 'integer',
    'querytypename': 'string',
    'queue_id': 'string',
    'rateavg': 'integer',
    'rateid': 'string',
    'ratemax': 'integer',
    'rateval': 'integer',
    'ratio': 'number',
    'raw_facility': 'string',
    'raw_facilityid': 'integer',
    'raw_mid': 'string',
    'raw_odt': 'string',
    'raw_omsg': 'string',
    'raw_pid': 'string',
    'raw_pri': 'integer',
    'raw_sdata': 'string',
    'raw_sev': 'string',
    'raw_sevid': 'integer',
    'rawmsg': 'string',
    'rawmsghostipv4': 'string',
    'rawmsghostipv6': 'string',
    'rawmsghostname': 'string',
    'rawmsgid': 'string',
    'rawmsgtimeutc': 'string',
    'rawsrchostname': 'string',
    'rcptto': 'string',
    'rcvdbodybytes': 'integer',
    'rcvdbytes': 'integer',
    'rcvdfileid': 'string',
    'rcvdipbytes': 'integer',
    'rcvdmimetype': 'string',
    'rcvdpackets': 'integer',
    'ready': 'boolean',
    'reason': 'string',
    'receptorhostid': 'string',
    'recordid': 'string',
    'recursionavailable': 'boolean',
    'recursiondesired': 'boolean',
    'referenceid': 'string',
    'referer': 'string',
    'referrer': 'string',
    'referrer_domain': 'string',
    'referrer_uri': 'string',
    'region': 'string',
    'regkey': 'string',
    'regpath': 'string',
    'regvalue': 'string',
    'rejected': 'boolean',
    'replay_datasource': 'string',
    'reply_code': 'number',
    'reply_msg': 'string',
    'replyto': 'string',
    'reportduration': 'integer',
    'request': 'string',
    'requestduration': 'number',
    'requestid': 'string',
    'requesttime': 'string',
    'requesttimeutc': 'string',
    'responder_heartbeats': 'number',
    'response': 'string',
    'responsecode': 'integer',
    'responsecodename': 'string',
    'restrictedsidcount': 'string',
    'result': 'string',
    'resumed': 'boolean',
    'rid': 'integer',
    'risk': 'string',
    'risklevel': 'integer',
    'roleid': 'string',
    'rt_version': 'object',
    'rule': 'string',
    'rulecat': 'string',
    'ruleid': 'string',
    'satori_blacklist': 'string',
    'saw_query': 'boolean',
    'saw_reply': 'boolean',
    'score': 'number',
    'second': 'string',
    'security_groups': 'object',
    'seenbytes': 'integer',
    'sensor': 'string',
    'sentbodybytes': 'integer',
    'sentbytes': 'integer',
    'sentfileid': 'string',
    'sentipbytes': 'integer',
    'sentmimetype': 'string',
    'sentpackets': 'integer',
    'serial': 'string',
    'server': 'string',
    'server_depth': 'number',
    'serveripv4': 'ipv4',
    'serveripv6': 'ipv6',
    'serverport': 'string',
    'serverstatuscode': 'integer',
    'servervars': 'string',
    'service': 'string',
    'serviceid': 'string',
    'sessionid': 'string',
    'sessionname': 'string',
    'sessiontype': 'string',
    'severity': 'string',
    'severityvalue': 'integer',
    'sha1': 'string',
    'sha256': 'string',
    'sha512': 'string',
    'signature': 'string',
    'signed': 'boolean',
    'site': 'string',
    'size': 'string',
    'sizeinram': 'number',
    'sizeondisk': 'number',
    'slot': 'string',
    'snort_alert': 'string',
    'source': 'string',
    'sourceclass': 'string',
    'sourceipaddress': 'string',
    'sourcemodulename': 'string',
    'sourcemoduletype': 'string',
    'srcareacode': 'string',
    'srcasn': 'string',
    'srcasorg': 'string',
    'srccity': 'string',
    'srccountry': 'string',
    'srccountrycode': 'string',
    'srcdomain': 'string',
    'srcelevation': 'number',
    'srchost': 'string',
    'srciddcode': 'string',
    'srcipv4': 'string',
    'srcipv6': 'string',
    'srcisp': 'string',
    'srclatitude': 'number',
    'srclocation': 'string',
    'srclongitude': 'string',
    'srcmac': 'string',
    'srcmcc': 'string',
    'srcmnc': 'string',
    'srcmobilebrand': 'string',
    'srcnatrule': 'string',
    'srcnetspeed': 'string',
    'srcport': 'integer',
    'srcregion': 'string',
    'srcserver': 'ipv4',
    'srctimezone': 'string',
    'srcusagetype': 'string',
    'srcweatherstationcode': 'string',
    'srcweatherstationname': 'string',
    'srczipcode': 'string',
    'srczone': 'string',
    'ssdeep': 'string',
    'ssid': 'string',
    'ssl': 'boolean',
    'starttime': 'string',
    'starttimeutc': 'string',
    'static_indicators': 'string',
    'stationid': 'string',
    'status': 'string',
    'status_changed_at_time': 'string',
    'statuscode': 'integer',
    'statusmsg': 'string',
    'strings': 'string',
    'stringval': 'string',
    'subfiletype': 'string',
    'subject': 'string',
    'submit_to_satori_at_time': 'string',
    'submittedAt': 'string',
    'submitted_by': 'string',
    'submitted_by_name': 'string',
    'subnet_id': 'string',
    'subsystem': 'string',
    'subtype': 'string',
    'suppressfor': 'integer',
    'system': 'string',
    'tags': 'string',
    'target': 'string',
    'targetdomain': 'string',
    'targethost': 'string',
    'targetip': 'string',
    'targetipv6': 'ipv6',
    'targetlogonid': 'string',
    'targetusername': 'string',
    'targetusersecurityid': 'string',
    'task': 'string',
    'tcp_details': 'object',
    'technique': 'string',
    'threadid': 'string',
    'threat': 'string',
    'threshold': 'number',
    'timedout': 'boolean',
    'timezone': 'string',
    'to': 'string',
    'total_bytes': 'number',
    'totalanswers': 'integer',
    'totalpages': 'integer',
    'totalreplies': 'integer',
    'track_address': 'number',
    'transactionid': 'string',
    'transdsthost': 'string',
    'transdstip': 'string',
    'transdstport': 'integer',
    'transsrchost': 'string',
    'transsrcip': 'string',
    'transsrcport': 'integer',
    'trigger_details': 'string',
    'truncationbit': 'boolean',
    'ttl': 'string',
    'tty': 'string',
    'tunnel_type': 'string',
    'tunnelparents': 'string',
    'type': 'integer',
    'type_details': 'object',
    'uid': 'integer',
    'unparsed_version': 'string',
    'uri': 'string',
    'uri_parsed': 'string',
    'url': 'string',
    'user_agent': 'string',
    'useragent': 'string',
    'usercheck': 'string',
    'usercheckid': 'string',
    'userchecklvl': 'string',
    'usercheckname': 'string',
    'username': 'string',
    'usersecurityid': 'string',
    'uses_aslr': 'boolean',
    'uses_code_integrity': 'boolean',
    'uses_dep': 'boolean',
    'uses_seh': 'boolean',
    'uuid': 'string',
    'version': 'string',
    'vhost': 'string',
    'virtualdomain': 'string',
    'virtualhost': 'string',
    'virus': 'string',
    'vlan': 'integer',
    'vlandesc': 'string',
    'vlanname': 'string',
    'volume': 'string',
    'vpc': 'string',
    'vt_first_seen': 'string',
    'vt_ratio': 'string',
    'webclient': 'string',
    'webclienttype': 'string',
    'webserver': 'string',
    'webservertype': 'string',
    'weight': 'number',
    'whitelist_info': 'string',
    'workstation': 'string',
    'x509': 'string',
    'xfwdforip': 'string',
    'yara_hits': 'string',
    'year': 'string',
    'zone': 'string',
}

# 日本語表示名（118件）。未定義のKEYは画面でKEY名をそのまま表示する。
LABELS: dict[str, str] = {
    'accountdomain': 'アカウントドメイン',
    'accountname': 'アカウント名',
    'action': 'アクション',
    'audit_acct': 'Auditアカウント',
    'audit_res': 'Audit結果',
    'audit_type': 'Audit種別',
    'audititemid': '監査項目ID',
    'authmethod': '認証方式',
    'bytes': 'バイト数',
    'callingdomain': '呼出元ドメイン',
    'callinglogonid': '呼出元ログオンID',
    'callingsrcip': '呼出元IP',
    'callingsrcipv6': '呼出元IPv6',
    'callingusername': '呼出元ユーザー',
    'callingusersecurityid': '呼出元ユーザーSID',
    'category': 'カテゴリ',
    'class': 'クラス',
    'description': 'メッセージ',
    'devicename': 'デバイス名',
    'domain': 'ドメイン',
    'dstasn': '宛先ASN',
    'dstasorg': '宛先AS組織',
    'dstcountry': '宛先国',
    'dstcountrycode': '宛先国コード',
    'dsthost': '宛先ホスト',
    'dstipv4': '宛先IPv4',
    'dstipv6': '宛先IPv6',
    'dstport': '宛先ポート',
    'errormessage': 'エラーメッセージ',
    'eventid': 'イベントID',
    'eventlog': 'イベントログ',
    'eventtime': 'イベント時刻',
    'eventtimeutc': 'イベント時刻(UTC)',
    'eventtype': 'イベント種別',
    'gid': 'GID',
    'group': 'グループ',
    'groupdomain': 'グループドメイン',
    'groupsecurityid': 'グループSID',
    'host': 'ホスト',
    'hostname': 'ホスト名',
    'httpmethod': 'HTTPメソッド',
    'keywords': 'キーワード',
    'logonguid': 'ログオンGUID',
    'logonid': 'ログオンID',
    'logontype': 'ログオン種別',
    'logontypeid': 'ログオンタイプ',
    'member': 'メンバー',
    'memberdomain': 'メンバードメイン',
    'membersecurityid': 'メンバーSID',
    'message': 'メッセージ',
    'mimetype': 'MIMEタイプ',
    'pid': 'PID',
    'ppid': '親PID',
    'pprocess': '親プロセス',
    'pprocesspath': '親プロセスパス',
    'privileges': '特権',
    'process': 'プロセス',
    'processid': 'プロセスID',
    'processpath': 'プロセスパス',
    'protocol': 'プロトコル',
    'protocolver': 'プロトコルバージョン',
    'providerguid': 'プロバイダーGUID',
    'query': 'クエリ',
    'rcvdbodybytes': '受信Bodyバイト数',
    'rcvdbytes': '受信バイト数',
    'reason': '理由',
    'recordid': 'レコードID',
    'referer': 'Referer',
    'referrer': 'Referrer',
    'referrer_domain': 'Refererドメイン',
    'referrer_uri': 'Referer URI',
    'request': 'リクエスト',
    'requestid': 'リクエストID',
    'result': '結果',
    'sentbodybytes': '送信Bodyバイト数',
    'sentbytes': '送信バイト数',
    'server': 'サーバー',
    'serveripv4': 'サーバーIPv4',
    'serveripv6': 'サーバーIPv6',
    'serverport': 'サーバーポート',
    'service': 'サービス',
    'serviceid': 'サービスID',
    'sessionid': 'セッションID',
    'severity': '重大度',
    'severityvalue': '重大度値',
    'srcasn': '送信元ASN',
    'srcasorg': '送信元AS組織',
    'srccountry': '送信元国',
    'srccountrycode': '送信元国コード',
    'srchost': '送信元ホスト',
    'srcipv4': '送信元IPv4',
    'srcipv6': '送信元IPv6',
    'srcport': '送信元ポート',
    'statuscode': 'ステータスコード',
    'statusmsg': 'ステータスメッセージ',
    'target': '対象',
    'targetdomain': '対象ドメイン',
    'targethost': '対象ホスト',
    'targetip': '対象IPv4',
    'targetipv6': '対象IPv6',
    'targetlogonid': '対象ログオンID',
    'targetusername': '対象ユーザー',
    'targetusersecurityid': '対象ユーザーSID',
    'task': 'タスク',
    'uid': 'UID',
    'uri': 'URI',
    'uri_parsed': '正規化URI',
    'url': 'URL',
    'user_agent': 'User-Agent',
    'useragent': 'User-Agent',
    'username': 'ユーザー名',
    'usersecurityid': 'ユーザーSID',
    'vhost': 'VHost',
    'virtualdomain': '仮想ドメイン',
    'virtualhost': '仮想ホスト',
    'webserver': 'Webサーバー',
    'workstation': 'ワークステーション',
    'xfwdforip': 'X-Forwarded-For',
}

# Class VALUE別の初期表示ヒント（taxonomy.md §6。既定列の算出にのみ使う）
CLASS_HINTS: dict[str, dict[str, dict]] = {
    'audit': {
        'accountdomain': {'default_visible': True},
        'accountname': {'default_visible': True},
        'action': {'default_visible': True},
        'audit_acct': {'default_visible': False},
        'audit_res': {'default_visible': False},
        'audit_type': {'default_visible': False},
        'audititemid': {'default_visible': False},
        'authmethod': {'default_visible': False},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': True},
        'dstipv4': {'default_visible': False},
        'dstipv6': {'default_visible': False},
        'dstport': {'default_visible': False},
        'eventid': {'default_visible': True},
        'eventtime': {'default_visible': True},
        'eventtimeutc': {'default_visible': False},
        'eventtype': {'default_visible': False},
        'gid': {'default_visible': False},
        'hostname': {'default_visible': True},
        'pid': {'default_visible': False},
        'ppid': {'default_visible': False},
        'pprocess': {'default_visible': False},
        'pprocesspath': {'default_visible': False},
        'process': {'default_visible': True},
        'processid': {'default_visible': False},
        'processpath': {'default_visible': False},
        'protocol': {'default_visible': False},
        'reason': {'default_visible': False},
        'requestid': {'default_visible': False},
        'result': {'default_visible': True},
        'service': {'default_visible': True},
        'sessionid': {'default_visible': False},
        'severity': {'default_visible': True},
        'severityvalue': {'default_visible': False},
        'srcipv4': {'default_visible': True},
        'srcipv6': {'default_visible': True},
        'srcport': {'default_visible': False},
        'target': {'default_visible': False},
        'targethost': {'default_visible': False},
        'targetip': {'default_visible': False},
        'targetipv6': {'default_visible': False},
        'targetusername': {'default_visible': True},
        'uid': {'default_visible': False},
        'username': {'default_visible': True},
    },
    'linux': {
        'accountdomain': {'default_visible': True},
        'accountname': {'default_visible': True},
        'action': {'default_visible': True},
        'authmethod': {'default_visible': False},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': True},
        'devicename': {'default_visible': False},
        'dstipv4': {'default_visible': False},
        'dstipv6': {'default_visible': False},
        'dstport': {'default_visible': False},
        'eventid': {'default_visible': True},
        'eventtime': {'default_visible': True},
        'eventtimeutc': {'default_visible': False},
        'eventtype': {'default_visible': False},
        'gid': {'default_visible': False},
        'hostname': {'default_visible': True},
        'pid': {'default_visible': False},
        'ppid': {'default_visible': False},
        'pprocess': {'default_visible': False},
        'pprocesspath': {'default_visible': False},
        'process': {'default_visible': True},
        'processid': {'default_visible': False},
        'processpath': {'default_visible': False},
        'protocol': {'default_visible': False},
        'reason': {'default_visible': False},
        'result': {'default_visible': True},
        'service': {'default_visible': True},
        'serviceid': {'default_visible': False},
        'sessionid': {'default_visible': False},
        'severity': {'default_visible': True},
        'severityvalue': {'default_visible': False},
        'srcipv4': {'default_visible': True},
        'srcipv6': {'default_visible': True},
        'srcport': {'default_visible': False},
        'target': {'default_visible': False},
        'targethost': {'default_visible': False},
        'targetip': {'default_visible': False},
        'targetipv6': {'default_visible': False},
        'targetusername': {'default_visible': True},
        'uid': {'default_visible': False},
        'username': {'default_visible': True},
    },
    'unknown': {
        'action': {'default_visible': True},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': True},
        'eventtime': {'default_visible': True},
        'hostname': {'default_visible': True},
        'result': {'default_visible': True},
        'severity': {'default_visible': True},
    },
    'web_access': {
        'accountname': {'default_visible': False},
        'action': {'default_visible': True},
        'bytes': {'default_visible': False},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': True},
        'domain': {'default_visible': False},
        'dstasn': {'default_visible': False},
        'dstasorg': {'default_visible': False},
        'dstcountry': {'default_visible': False},
        'dstcountrycode': {'default_visible': False},
        'dsthost': {'default_visible': False},
        'dstipv4': {'default_visible': False},
        'dstipv6': {'default_visible': False},
        'dstport': {'default_visible': False},
        'eventtime': {'default_visible': True},
        'eventtimeutc': {'default_visible': False},
        'host': {'default_visible': False},
        'httpmethod': {'default_visible': True},
        'mimetype': {'default_visible': False},
        'protocol': {'default_visible': False},
        'protocolver': {'default_visible': False},
        'query': {'default_visible': False},
        'rcvdbodybytes': {'default_visible': False},
        'rcvdbytes': {'default_visible': False},
        'reason': {'default_visible': False},
        'referer': {'default_visible': False},
        'referrer': {'default_visible': False},
        'referrer_domain': {'default_visible': False},
        'referrer_uri': {'default_visible': False},
        'request': {'default_visible': False},
        'requestid': {'default_visible': False},
        'result': {'default_visible': True},
        'sentbodybytes': {'default_visible': False},
        'sentbytes': {'default_visible': False},
        'server': {'default_visible': False},
        'serveripv4': {'default_visible': False},
        'serveripv6': {'default_visible': False},
        'serverport': {'default_visible': False},
        'sessionid': {'default_visible': False},
        'severity': {'default_visible': True},
        'severityvalue': {'default_visible': False},
        'srcasn': {'default_visible': False},
        'srcasorg': {'default_visible': False},
        'srccountry': {'default_visible': False},
        'srccountrycode': {'default_visible': False},
        'srchost': {'default_visible': False},
        'srcipv4': {'default_visible': True},
        'srcipv6': {'default_visible': True},
        'srcport': {'default_visible': False},
        'statuscode': {'default_visible': True},
        'statusmsg': {'default_visible': False},
        'uri': {'default_visible': True},
        'uri_parsed': {'default_visible': False},
        'url': {'default_visible': False},
        'user_agent': {'default_visible': False},
        'useragent': {'default_visible': False},
        'username': {'default_visible': False},
        'vhost': {'default_visible': False},
        'virtualdomain': {'default_visible': True},
        'virtualhost': {'default_visible': False},
        'webserver': {'default_visible': False},
        'xfwdforip': {'default_visible': False},
    },
    'web_error': {
        'accountname': {'default_visible': True},
        'action': {'default_visible': True},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': True},
        'domain': {'default_visible': False},
        'dstipv4': {'default_visible': False},
        'dstipv6': {'default_visible': False},
        'dstport': {'default_visible': False},
        'errormessage': {'default_visible': False},
        'eventid': {'default_visible': True},
        'eventtime': {'default_visible': True},
        'eventtimeutc': {'default_visible': False},
        'eventtype': {'default_visible': False},
        'host': {'default_visible': False},
        'hostname': {'default_visible': True},
        'httpmethod': {'default_visible': True},
        'pid': {'default_visible': False},
        'ppid': {'default_visible': False},
        'pprocess': {'default_visible': False},
        'pprocesspath': {'default_visible': False},
        'process': {'default_visible': True},
        'processid': {'default_visible': False},
        'processpath': {'default_visible': False},
        'protocol': {'default_visible': False},
        'query': {'default_visible': False},
        'reason': {'default_visible': False},
        'result': {'default_visible': True},
        'server': {'default_visible': False},
        'serveripv4': {'default_visible': False},
        'serveripv6': {'default_visible': False},
        'serverport': {'default_visible': False},
        'service': {'default_visible': True},
        'severity': {'default_visible': True},
        'severityvalue': {'default_visible': False},
        'srcipv4': {'default_visible': True},
        'srcipv6': {'default_visible': True},
        'srcport': {'default_visible': False},
        'statuscode': {'default_visible': True},
        'statusmsg': {'default_visible': False},
        'uri': {'default_visible': True},
        'url': {'default_visible': False},
        'username': {'default_visible': True},
        'vhost': {'default_visible': False},
        'virtualdomain': {'default_visible': True},
        'virtualhost': {'default_visible': False},
        'webserver': {'default_visible': False},
    },
    'windows_event': {
        'accountdomain': {'default_visible': True},
        'accountname': {'default_visible': True},
        'action': {'default_visible': True},
        'authmethod': {'default_visible': False},
        'callingdomain': {'default_visible': False},
        'callinglogonid': {'default_visible': False},
        'callingsrcip': {'default_visible': False},
        'callingsrcipv6': {'default_visible': False},
        'callingusername': {'default_visible': False},
        'callingusersecurityid': {'default_visible': False},
        'category': {'default_visible': True},
        'class': {'default_visible': True},
        'description': {'default_visible': False},
        'devicename': {'default_visible': False},
        'dstipv4': {'default_visible': False},
        'dstipv6': {'default_visible': False},
        'dstport': {'default_visible': False},
        'eventid': {'default_visible': True},
        'eventlog': {'default_visible': True},
        'eventtime': {'default_visible': True},
        'eventtimeutc': {'default_visible': False},
        'eventtype': {'default_visible': False},
        'group': {'default_visible': False},
        'groupdomain': {'default_visible': False},
        'groupsecurityid': {'default_visible': False},
        'hostname': {'default_visible': True},
        'keywords': {'default_visible': False},
        'logonguid': {'default_visible': False},
        'logonid': {'default_visible': False},
        'logontype': {'default_visible': False},
        'logontypeid': {'default_visible': True},
        'member': {'default_visible': False},
        'memberdomain': {'default_visible': False},
        'membersecurityid': {'default_visible': False},
        'message': {'default_visible': True},
        'pid': {'default_visible': False},
        'ppid': {'default_visible': False},
        'pprocess': {'default_visible': False},
        'pprocesspath': {'default_visible': False},
        'privileges': {'default_visible': False},
        'process': {'default_visible': True},
        'processid': {'default_visible': False},
        'processpath': {'default_visible': False},
        'providerguid': {'default_visible': False},
        'reason': {'default_visible': False},
        'recordid': {'default_visible': False},
        'result': {'default_visible': True},
        'service': {'default_visible': True},
        'sessionid': {'default_visible': False},
        'severity': {'default_visible': True},
        'severityvalue': {'default_visible': False},
        'srcipv4': {'default_visible': True},
        'srcipv6': {'default_visible': True},
        'srcport': {'default_visible': False},
        'targetdomain': {'default_visible': False},
        'targethost': {'default_visible': False},
        'targetip': {'default_visible': False},
        'targetipv6': {'default_visible': False},
        'targetlogonid': {'default_visible': False},
        'targetusername': {'default_visible': True},
        'targetusersecurityid': {'default_visible': False},
        'task': {'default_visible': False},
        'username': {'default_visible': True},
        'usersecurityid': {'default_visible': False},
        'workstation': {'default_visible': False},
    },
}


# 大文字小文字を無視した照合用の索引: lower(KEY) -> Taxonomy KEY（正規表記）
_LOWER: dict[str, str] = {k.lower(): k for k in ALL_KEYS}


def canonical_key(key: str) -> str | None:
    """受信KEYに対応するTaxonomy KEY（正規表記）。無ければNone。

    照合は大文字小文字を区別しない。`EventTime` / `EVENTTIME` / `Eventtime` はいずれも
    Taxonomy KEY `eventtime` として扱う。**受信payloadのKEY名自体は変更しない**
    （保存時の読み替えではなく、Taxonomyを参照するときだけ lower() で突き合わせる）。

    大文字小文字の差ではなくKEY名そのものが違うものは一致しない:
      host != hostname / vhost != virtualhost / client != srcipv4 / time != eventtime
    """
    return _LOWER.get(key.lower())


def is_taxonomy_key(key: str) -> bool:
    """受信KEYがTaxonomy KEYに一致するか（大文字小文字は区別しない。v12 §4.1.1）。"""
    return key.lower() in _LOWER


def label_of(key: str) -> str | None:
    """日本語表示名。未定義ならNone（呼び出し側はKEY名をそのまま表示する）。"""
    c = canonical_key(key)
    return LABELS.get(c) if c else None


def default_columns(class_value: str | None) -> list[str]:
    """そのClassの既定表示列。taxonomy.md §6で「初期表示=表示」のKEY。
    §6に参考例が無いClass VALUEでも動く必要があるため、無ければ汎用の最小セットを返す。
    """
    hints = CLASS_HINTS.get(class_value or '')
    if hints:
        return [k for k, v in hints.items() if v['default_visible']]
    generic = ['class', 'eventtime', 'hostname', 'description']
    return [k for k in generic if k in ALL_KEYS]
